fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
challenge:
    resource: "@ChallengeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
